### ISSUE TITLE
Multi-line code blocks and syntax highlighting

### ISSUE THREAD

**Issue by ozanvos** [hugoduncan/codox-md#3]
Is there any chance codox-md could render multi-line code blocks wrapped in two ```s and apply syntax highlighting

``` clojure
[:like :github]?
```

**Comment by JulianBirch** [comment]
Hi, I've got an implentation of this.  You can see the WIP output [here](http://julianbirch.github.io/arianna/arianna.html).

It's currently a completely separate project that uses codox-md, but I could turn it into a pull request.  However, there are a number of things you should know about it:
- It uses pygments (via jython)
- It uses endophile (so a new markdown engine)

In short, it's a big change, so I could send you a PR or release it as an independent project that uses codox-md as a library.
